version: "3"
services:
   logs-mysql:
      image: mysql:5.7
      environment: 
         - MYSQL_ROOT_PASSWORD=rootroot
      ports:
         - "3306"
   logs-redis: 
      image: redis
      ports:
         - "6379"
      entrypoint:
         - redis-server
         - --appendonly
         - yes
   device-logs:
      build:
         context: .
         dockerfile: Dockerfile
      depends_on:
         - logs-mysql
         - logs-redis